ui: mocha-bdd
browsers:
  - name: chrome
    version: latest
  - name: ie
    version: 9..latest
  - name: firefox
    version: latest
  - name: safari
    version: latest
browserify:
  - transform: brfs
  - options:
      transform: brfs
